databases:
  - name: puzzlehunt_postgres
    databaseName: puzzlehunt_postgres # optional (Render may add a suffix)
    user: puzzlehunt # optional
    plan: free

services:
  - type: web
    name: puzzlehunt_prod
    env: ruby
    plan: free
    healthCheckPath: /health
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: puzzlehunt_postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: ACCESS_KEY_ID
        sync: false
      - key: SECRET_ACCESS_KEY
        sync: false
